### ISSUE TITLE
Bluetooth permission?

### ISSUE THREAD

**Issue by Rudloff** [mapswipe/yourmapswipe-react-native-app#3]
Hello,

It seems this app requests access to Bluetooth devices: https://github.com/mapswipe/yourmapswipe-react-native-app/blob/c198104041810bb1a1eb00f682c1d3946270fb96/android/app/src/main/AndroidManifest.xml#L16
Is this really necessary? I don't really see what functionnality would need to use Bluetooth.

**Comment by PimDeWitte** [comment]
There is no reason for it to be there. It must have been automatically included with one of the libraries I implemented.
